### PR TITLE
ability to configure Youtube Player Parameters

### PR DESCRIPTION
**Pull request by NihilisticNive25**

### CODE REVIEW

**Comment by souporserious** [comment]
Thanks for the PR! Can you please rename to just `config` and use an object. I'd like to mimic what [react-player does in this scenario](https://www.npmjs.com/package/react-player#config-prop) and eventually add configuration options for other vendors.

**Comment by NihilisticNive25** [comment]
You are right. I have modified accordingly and raised a PR. Let me know if I need to change any.
Would you like me to change the video example with Youtube start and end time?

**Comment by souporserious** [comment]
Thank you for this PR! I was right in the middle of getting married when you created this so apologies for the late reply. There were some changes that I had to make so I added them in a new PR (#75). It's also been published on NPM so hopefully, it fixes your issue. Thanks again! 🙏

**Comment by NihilisticNive25** [comment]
Thank you for publishing the feature on NPM. 
Congrats & Wishing you a lifetime of love and happiness.

**Pull request closed without merging**
